apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: zhoujie-devsecops-demo  
  namespace: zhoujie-devsecops
  labels:  
    app: zhoujie-devsecops-demo  
spec:  
  replicas: 2  
  selector:  
    matchLabels:  
      app: zhoujie-devsecops-demo  
  template:  
    metadata:  
      labels:  
        app: zhoujie-devsecops-demo  
    spec:  
      topologySpreadConstraints:  
        - maxSkew: 1  
          topologyKey: topology.kubernetes.io/zone  
          whenUnsatisfiable: DoNotSchedule  
          labelSelector:  
            matchLabels:  
              app: zhoujie-devsecops-demo  
      containers:  
        - name: zhoujie-devsecops-demo  
          image: 253685958295.dkr.ecr.us-east-2.amazonaws.com/zhoujie-devsecops-demo:23  
          ports:  
            - containerPort: 8080  
---
apiVersion: v1  
kind: Service  
metadata:  
  name: zhoujie-devsecops-demo-svc  
  namespace: zhoujie-devsecops
  labels:  
    app: zhoujie-devsecops-demo  
spec:  
  type: NodePort  
  selector:  
    app: zhoujie-devsecops-demo  
  ports:  
    - port: 80  
      targetPort: 8080  
      protocol: TCP  
      nodePort: 31000  
